server:
  port: 8081

spring:
  application:
    name: docmind-api

  datasource:
    url: jdbc:postgresql://localhost:5433/docmind
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}

        chat:
          options:
            model: gemini-2.5-flash

        embedding:
          api-key: ${GEMINI_API_KEY}
          vertex-ai: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
